# Generated by Django 5.2.8 on 2025-11-27 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('administration', 'Administration'), ('teaching', 'Enseignement'), ('infrastructure', 'Infrastructure'), ('harassment', 'Harcèlement'), ('discrimination', 'Discrimination'), ('financial', 'Financier'), ('technical', 'Technique'), ('other', 'Autre')], help_text='Type de réclamation', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de réclamation',
                'verbose_name_plural': 'Catégories de réclamations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique du ticket pour le suivi anonyme', unique=True)),
                ('access_key', models.CharField(help_text='Clé secrète pour accéder au ticket de manière anonyme', max_length=64)),
                ('title', models.CharField(help_text='Titre de la réclamation', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée de la réclamation')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('rejected', 'Rejeté'), ('closed', 'Fermé')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('is_anonymous', models.BooleanField(default=True, help_text='Indique si la réclamation est anonyme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP (pour audit de sécurité uniquement)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent du navigateur (pour audit)')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'administrator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reclamations', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant soumis la réclamation (null si anonyme)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='reclamations.reclamationcategory')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReclamationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Fichier joint à la réclamation', upload_to='reclamations/attachments/%Y/%m/%d/')),
                ('filename', models.CharField(help_text='Nom original du fichier', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Taille du fichier en octets')),
                ('content_type', models.CharField(help_text='Type MIME du fichier', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reclamations.reclamation')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReclamationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_submitter', models.BooleanField(default=False, help_text='Indique si le commentaire vient du soumetteur anonyme')),
                ('is_internal', models.BooleanField(default=False, help_text='Note interne visible uniquement par les administrateurs')),
                ('content', models.TextField(help_text='Contenu du commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamation_comments', to=settings.AUTH_USER_MODEL)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reclamations.reclamation')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReclamationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('rejected', 'Rejeté'), ('closed', 'Fermé')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('rejected', 'Rejeté'), ('closed', 'Fermé')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Raison du changement de statut')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reclamations.reclamation')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statuts',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['ticket_id'], name='reclamation_ticket__5c79c5_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['status', 'created_at'], name='reclamation_status_a73dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['category', 'status'], name='reclamation_categor_87852c_idx'),
        ),
    ]
