# Generated by Django 5.2.8 on 2025-11-27 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reclamationattachment',
            name='reclamation',
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='category',
            field=models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('ENSEIGNEMENT', 'Enseignement'), ('INFRASTRUCTURE', 'Infrastructure'), ('HARCELEMENT', 'Harcèlement'), ('AUTRES', 'Autres')], default='AUTRES', max_length=50),
        ),
        migrations.RemoveField(
            model_name='reclamationcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reclamationcomment',
            name='reclamation',
        ),
        migrations.RemoveField(
            model_name='reclamationstatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='reclamationstatushistory',
            name='reclamation',
        ),
        migrations.AlterModelOptions(
            name='reclamation',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='reclamation',
            name='reclamation_ticket__5c79c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='reclamation',
            name='reclamation_status_a73dd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='reclamation',
            name='reclamation_categor_87852c_idx',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reclamations/'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='status',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté')], default='NOUVEAU', max_length=20),
        ),
        migrations.AddField(
            model_name='reclamationhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamationhistory',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reclamations.reclamation'),
        ),
        migrations.DeleteModel(
            name='ReclamationAttachment',
        ),
        migrations.DeleteModel(
            name='ReclamationCategory',
        ),
        migrations.DeleteModel(
            name='ReclamationComment',
        ),
        migrations.DeleteModel(
            name='ReclamationStatusHistory',
        ),
    ]
