# Generated by Django 4.2.19 on 2025-12-10 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cin',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='diploma',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Ex: 2023-2024', max_length=9)),
                ('registration_id', models.IntegerField()),
                ('grade', models.CharField(choices=[('1ere', '1ère année'), ('2eme', '2ème année'), ('3eme', '3ème année')], max_length=10)),
                ('specialty', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('session', models.CharField(choices=[('principale', 'Principale'), ('controle', 'Contrôle')], max_length=20)),
                ('result', models.CharField(choices=[('tres_bien', 'Très Bien'), ('bien', 'Bien'), ('assez_bien', 'Assez Bien'), ('passable', 'Passable'), ('ajourne', 'Ajourné')], max_length=20)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='education_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Education histories',
                'ordering': ('-academic_year',),
            },
        ),
    ]
