# Generated by Django 4.2.19 on 2025-12-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cin_user_date_of_birth_user_diploma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name_arabic',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_arabic',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='diploma',
            field=models.CharField(choices=[('Licence en Ingénierie des Systèmes Informatiques', 'Licence en Ingénierie des Systèmes Informatiques'), ('Licence en Génie Mécanique', 'Licence en Génie Mécanique'), ('Licence en Génie énergétique', 'Licence en Génie énergétique'), ('Licence en électronique électrotechnique & Automatique', 'Licence en électronique électrotechnique & Automatique'), ('Master Recherche en data science', 'Master Recherche en data science'), ('Master Recherche en Automatique & Informatique Industrielle', 'Master Recherche en Automatique & Informatique Industrielle'), ('Master Professionnel en Commandes des Systémes Industriels', 'Master Professionnel en Commandes des Systémes Industriels'), ('Master Professionnel en Gestion de Maintenance des Systémes Industriels', 'Master Professionnel en Gestion de Maintenance des Systémes Industriels'), ('Master Professionnel en génie mécanique', 'Master Professionnel en génie mécanique')], help_text="Diplôme obtenu par l'utilisateur.", max_length=80),
        ),
    ]
