# Generated by Django 4.2.19 on 2025-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_first_name_arabic_user_last_name_arabic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place_of_birth_arabic',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='grade',
            field=models.CharField(choices=[('1', 'Première année'), ('2', 'Deuxième année'), ('3', 'Troisième année')], max_length=10),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='specialty',
            field=models.CharField(default='Tronc Commun', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='diploma',
            field=models.CharField(choices=[('Licence en Ingénierie des Systèmes Informatiques', 'إجازة في هندسة أنظمة المعلومات'), ('Licence en Génie Mécanique', 'إجازة في الهندسة الميكانيكية'), ('Licence en Génie énergétique', 'إجازة في الهندسة الطاقية'), ('Licence en électronique électrotechnique & Automatique', 'إجازة في الإلكترونيات الكهرتقنية والآلية'), ('Master Recherche en data science', 'ماجستير بحث في علوم البيانات'), ('Master Recherche en Automatique & Informatique Industrielle', 'ماجستير بحث في الآلية والحوسبة الصناعية'), ('Master Professionnel en Commandes des Systémes Industriels', 'ماجستير مهني في قيادة الأنظمة الصناعية'), ('Master Professionnel en Gestion de Maintenance des Systémes Industriels', 'ماجستير مهني في إدارة صيانة الأنظمة الصناعية'), ('Master Professionnel en génie mécanique', 'ماجستير مهني في الهندسة الميكانيكية')], help_text="Diplôme obtenu par l'utilisateur.", max_length=80),
        ),
    ]
