# Generated by Django 5.2.9 on 2025-12-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_place_of_birth_arabic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant'), ('administrator', 'Responsable Administratif'), ('scolar_administrator', 'Responsable scolaire'), ('club_manager', 'Gestionnaire de Club')], default='student', help_text='Profil fonctionnel tel que défini dans le cahier des charges.', max_length=32),
        ),
    ]
