from django.urls import path
from .views import (
    DocumentRequestListCreateView,
    DocumentRequestDetailView,
    TerminateDocumentRequestView,
    RejectDocumentRequestView,
    ProcessDocumentRequestView,
    DocumentRequestFileView,
    DocumentRequestUploadFileView,
    GenerateInscriptionCertificateView,
    GeneratePresenceCertificateView,
    GenerateSuccessCertificateView,
    PresenceRequestCreateView,
    PresenceRequestApprovalListView,
    PresenceRequestApprovalDetailView,
)

app_name = 'document_requests'

urlpatterns = [
    path(
        "demandes/",
        DocumentRequestListCreateView.as_view(),
        name="document-request-list-create",
    ),
    path(
        "demandes/<uuid:public_id>/",
        DocumentRequestDetailView.as_view(),
        name="document-request-detail",
    ),
    path(
        "demandes/<uuid:public_id>/terminate/",
        TerminateDocumentRequestView.as_view(),
        name="document-request-terminate",
    ),
    path(
        "demandes/<uuid:public_id>/reject/",
        RejectDocumentRequestView.as_view(),
        name="document-request-reject",
    ),
    path(
        "demandes/<uuid:public_id>/process/",
        ProcessDocumentRequestView.as_view(),
        name="document-request-process",
    ),
    path(
        "demandes/<uuid:public_id>/file/",
        DocumentRequestFileView.as_view(),
        name="document-request-file",
    ),
    path(
        "demandes/<uuid:public_id>/upload-file/",
        DocumentRequestUploadFileView.as_view(),
        name="document-request-upload-file",
    ),
    path(
        "demandes/<uuid:public_id>/generate-inscription-certificate/",
        GenerateInscriptionCertificateView.as_view(),
        name="generate-inscription-certificate",
    ),
    path(
        "demandes/<uuid:public_id>/generate-presence-certificate/",
        GeneratePresenceCertificateView.as_view(),
        name="generate-presence-certificate",
    ),
    path(
        "demandes/<uuid:public_id>/generate-success-certificate/",
        GenerateSuccessCertificateView.as_view(),
        name="generate-success-certificate",
    ),
    # Presence request specific endpoints
    path(
        "presence-requests/",
        PresenceRequestCreateView.as_view(),
        name="presence-request-create",
    ),
    path(
        "teacher/approvals/",
        PresenceRequestApprovalListView.as_view(),
        name="presence-request-approval-list",
    ),
    path(
        "teacher/approvals/<int:id>/",
        PresenceRequestApprovalDetailView.as_view(),
        name="presence-request-approval-detail",
    ),
]
