# Generated by Django 4.2.19 on 2025-12-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabe'), ('fr', 'Français')], default='ar', max_length=2),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='document_requests/pdfs/'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='reception_type',
            field=models.CharField(choices=[('ONLINE', 'En ligne'), ('PERSONAL', 'En personne'), ('BOTH', 'Les deux')], default='BOTH', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('TRANSCRIPT', 'Relevé de notes'), ('CERTIFICATE_PRESENCE', 'Attestation de présence'), ('CERTIFICATE_SUCCESS', 'Attestation de réussite'), ('CERTIFICATE_INSCRIPTION', "Attestation d'inscription"), ('DIPLOMA', 'Diplôme'), ('OTHER', 'Autre')], default='OTHER', max_length=50),
        ),
    ]
