# Generated by Django 4.2.19 on 2025-12-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0002_documentrequest_language_documentrequest_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='document_requests/pdfs/'),
        ),
    ]
