# Generated by Django 4.2.19 on 2025-12-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0003_alter_documentrequest_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='academic_year',
            field=models.CharField(default='2025-2026', help_text='Ex: 2023-2024', max_length=9),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='pdf_requested_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='document_requests/pdfs/requested/'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='document_requests/pdfs/demandes/'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('IN_PROGRESS', 'En cours'), ('READY', 'Prêt'), ('REJECTED', 'Rejeté'), ('DELIVERED', 'Livré')], default='NEW', max_length=20),
        ),
    ]
