# Generated by Django 4.2.19 on 2025-12-13 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_requests', '0004_documentrequest_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceRequestApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_request', models.ForeignKey(limit_choices_to={'document_type': 'CERTIFICATE_PRESENCE'}, on_delete=django.db.models.deletion.CASCADE, related_name='presence_approvals', to='document_requests.documentrequest')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='presence_request_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presence Request Approval',
                'verbose_name_plural': 'Presence Request Approvals',
                'unique_together': {('document_request', 'teacher')},
            },
        ),
    ]
